server:
  port: 8090
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.0.8.11:3306/oauth2sso?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: oauth2sso
      password: oauth2sso
      filter: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3600000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  level:
    club.bannerstudio.oauth2sso: debug
    org.springfromework.web: info
    com.baomidou.mybatisplus: error
    file:
      name: log\oauth2sso.log
  #  邮箱
  mail:
    host: smtp.qq.com
    port: 587
    username: 2952434583@qq.com
    password: spmkmsoighssdhdd
    default-encoding: UTF-8
    properties:
      smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
      debug: true
  #redis
  redis:
    host: 10.0.8.11
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl